// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3adtwsaNx4fbnhR9s4awSb
// Component: 6VIAcnaHASJ_Lz
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic_copy_of_planty.module.css"; // plasmic-import: 3adtwsaNx4fbnhR9s4awSb/projectcss
import sty from "./PlasmicRatings.module.css"; // plasmic-import: 6VIAcnaHASJ_Lz/css
import StarIcon from "./icons/PlasmicIcon__Star"; // plasmic-import: 7WcldtXECqzl9W/icon

export const PlasmicRatings__VariantProps = new Array("stars");

export const PlasmicRatings__ArgProps = new Array("numReviews");

function PlasmicRatings__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_library_plasmic_color_type_css.plasmic_tokens,
        sty.root,
        {
          [sty.rootstars_five]: hasVariant(variants, "stars", "five"),
          [sty.rootstars_four]: hasVariant(variants, "stars", "four"),
          [sty.rootstars_one]: hasVariant(variants, "stars", "one"),
          [sty.rootstars_three]: hasVariant(variants, "stars", "three"),
          [sty.rootstars_two]: hasVariant(variants, "stars", "two"),
          [sty.rootstars_zero]: hasVariant(variants, "stars", "zero")
        }
      )}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        {(hasVariant(variants, "stars", "zero") ? true : true) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__hGi2, {
              [sty.svgstars_five__hGi2MN0CM]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svgstars_zero__hGi2Pesu7]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? true
            : hasVariant(variants, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__sCuBm, {
              [sty.svgstars_five__sCuBmmN0CM]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svgstars_four__sCuBmJpA84]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svgstars_one__sCuBmIdMr]: hasVariant(
                variants,
                "stars",
                "one"
              ),

              [sty.svgstars_three__sCuBm4TXrk]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svgstars_two__sCuBms7XsB]: hasVariant(
                variants,
                "stars",
                "two"
              ),

              [sty.svgstars_zero__sCuBmPesu7]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? true
            : hasVariant(variants, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__djTDj, {
              [sty.svgstars_five__djTDjmN0CM]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svgstars_four__djTDjJpA84]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svgstars_one__djTDjIdMr]: hasVariant(
                variants,
                "stars",
                "one"
              ),

              [sty.svgstars_three__djTDj4TXrk]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svgstars_two__djTDjs7XsB]: hasVariant(
                variants,
                "stars",
                "two"
              ),

              [sty.svgstars_zero__djTDjPesu7]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? true
            : hasVariant(variants, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg___1PXwM, {
              [sty.svgstars_five___1PXwMmN0CM]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svgstars_four___1PXwMJpA84]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svgstars_one___1PXwMIdMr]: hasVariant(
                variants,
                "stars",
                "one"
              ),

              [sty.svgstars_three___1PXwM4TXrk]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svgstars_two___1PXwMs7XsB]: hasVariant(
                variants,
                "stars",
                "two"
              ),

              [sty.svgstars_zero___1PXwMpesu7]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? true
            : hasVariant(variants, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__jd93N, {
              [sty.svgstars_five__jd93NmN0CM]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svgstars_four__jd93NJpA84]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svgstars_one__jd93NIdMr]: hasVariant(
                variants,
                "stars",
                "one"
              ),

              [sty.svgstars_three__jd93N4TXrk]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svgstars_two__jd93Ns7XsB]: hasVariant(
                variants,
                "stars",
                "two"
              ),

              [sty.svgstars_zero__jd93NPesu7]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? true
            : hasVariant(variants, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__dR1Pb, {
              [sty.svgstars_five__dR1PbmN0CM]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svgstars_four__dR1PbJpA84]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svgstars_one__dR1PbIdMr]: hasVariant(
                variants,
                "stars",
                "one"
              ),

              [sty.svgstars_three__dR1Pb4TXrk]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svgstars_two__dR1Pbs7XsB]: hasVariant(
                variants,
                "stars",
                "two"
              ),

              [sty.svgstars_zero__dR1PbPesu7]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__jqRz, {
              [sty.svgstars_five__jqRzmN0CM]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svgstars_four__jqRzJpA84]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svgstars_three__jqRz4TXrk]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svgstars_two__jqRzs7XsB]: hasVariant(
                variants,
                "stars",
                "two"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__aUsF4, {
              [sty.svgstars_five__aUsF4MN0CM]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svgstars_four__aUsF4JpA84]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svgstars_three__aUsF44TXrk]: hasVariant(
                variants,
                "stars",
                "three"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__zNnSw, {
              [sty.svgstars_five__zNnSwmN0CM]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svgstars_four__zNnSwJpA84]: hasVariant(
                variants,
                "stars",
                "four"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(hasVariant(variants, "stars", "five") ? true : true) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__yOx20, {
              [sty.svgstars_five__yOx20MN0CM]: hasVariant(
                variants,
                "stars",
                "five"
              )
            })}
            role={"img"}
          />
        ) : null}
      </p.Stack>

      {p.renderPlasmicSlot({
        defaultContents: "(45 Review)",
        value: args.numReviews,
        className: classNames(sty.slotTargetNumReviews)
      })}
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicRatings__ArgProps,
      internalVariantPropNames: PlasmicRatings__VariantProps
    });

    return PlasmicRatings__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRatings";
  } else {
    func.displayName = `PlasmicRatings.${nodeName}`;
  }
  return func;
}

export const PlasmicRatings = Object.assign(
  // Top-level PlasmicRatings renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    // Metadata about props expected for PlasmicRatings
    internalVariantProps: PlasmicRatings__VariantProps,
    internalArgProps: PlasmicRatings__ArgProps
  }
);

export default PlasmicRatings;
/* prettier-ignore-end */
